vich_uploader:
    db_driver: orm

    mappings:
        categorie_image:
            uri_prefix: /uploads/categorie
            upload_destination: '%kernel.project_dir%/public/uploads/categorie'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        preuve_image:
            uri_prefix: /uploads/preuve
            upload_destination: '%kernel.project_dir%/public/uploads/preuve'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer